version: '3.7'

services:
  web:
    build: .
    ports:
    - "8080:80"
    - "1443:443"
    volumes:
    - .:/opt/app/
    links:
    - db
  db:
    image: mysql:5.7
    ports:
    - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=q1w2e3r4
      - MYSQL_DATABASE=app
